[pytest]
testpaths = tests
pythonpath = .
addopts = -ra --import-mode=importlib
markers =
    external: harici bağlantı gerektiren testler
    integration: Harici bileşen kullanan bütünleşme testleri
    end_to_end: Gerçek uçtan uca sistem testleri
